[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './confirmation.html',
    './node_modules/**',
  ]

[[redirects]]
https://wordpress.rootscope.dev/* https://wp-maintenance.pro/:splat 301!