[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './confirmation.html',
    './node_modules/**',
  ]

[[redirects]]
  from = "https://wordpress.rootscope.dev/*"
  to = "https://wp-maintenance.pro/:splat"
  status = 301
  force = true
